steps:
- name: 'gcr.io/cloud-builders/npm'
  dir: /workspace/api
  args: ["install"]

- name: 'gcr.io/cloud-builders/npm'
  dir: /workspace/api
  args: ["run", "test"]

- name: 'gcr.io/cloud-builders/docker'
  args: [ "build", "-t", "botfront-api-local", "./api"]

- name: 'gcr.io/cloud-builders/docker'
  args: [ "build",  "-t", "botfront-local", "."]

- name: 'gcr.io/kaniko-project/executor:latest'
  dir: /workspace/botfront/cypress
  args:
  - --dockerfile=Dockerfile_cypress
  - --context=/workspace/botfront/cypress
  - --destination=gcr.io/$PROJECT_ID/cypress-runner:latest
  - --cache=true
  - --cache-ttl=24h

- name: docker.io/docker/compose:1.24.1
  dir: /workspace/botfront/cypress
  args:
    - up
    - --abort-on-container-exit
    - --exit-code-from
    - e2e

- name: 'gcr.io/cloud-builders/docker'
  args: [ "tag", "botfront-local", "botfront/botfront:branch-$BRANCH_NAME"]

- name: 'gcr.io/cloud-builders/docker'
  args: [ "tag", "botfront-api-local", "botfront/botfront-api:branch-$BRANCH_NAME"]

- name: 'gcr.io/cloud-builders/npm'
  dir: './botfront'
  args: [ "run",  "docs:build"]

- name: 'gcr.io/cloud-builders/docker'
  args: [ "build",  "-t", "botfront/botfront-docs:branch-$BRANCH_NAME", "./botfront/docs"]

- name: 'gcr.io/cloud-builders/docker'
  args: [ "login",
        "-u", "$_DOCKER_USERNAME",
        "-p", "$_DOCKER_PASSWORD",
  ]

- name: 'gcr.io/cloud-builders/docker'
  args: [ "push", "botfront/botfront:branch-$BRANCH_NAME"]

- name: 'gcr.io/cloud-builders/docker'
  args: [ "push", "botfront/botfront-api:branch-$BRANCH_NAME"]

- name: 'gcr.io/cloud-builders/docker'
  args: [ "push", "botfront/botfront-docs:branch-$BRANCH_NAME"]

timeout: 120m
