steps:
- name: 'gcr.io/cloud-builders/npm'
  dir: /workspace/api
  args: ["install"]
  
- name: 'gcr.io/cloud-builders/npm'
  dir: /workspace/api
  args: ["run", "test"]

- name: 'gcr.io/cloud-builders/docker'
  args: [ "build", "-t", "botfront-api-local", "./api"]

- name: 'gcr.io/cloud-builders/docker'
  args: [ "build",  "-t", "botfront-local", "."]

- name: docker.io/docker/compose:1.24.1
  dir: /workspace/botfront/cypress
  args:
    - up
    - --abort-on-container-exit
    - --exit-code-from
    - e2e

timeout: 7200s