steps:
# - name: 'gcr.io/cloud-builders/docker'
#   args: ['build', '-f', './ci/Dockerfile.ubuntu-curl', '-t', 'script-runner', '.']
# - name: 'script-runner'
#   args: ['bash', './ci/install_meteor.bash']
- name: 'ubuntu'
  dir: botfront
  args: ['bash', 'meteor', 'npm', 'install']
- name: 'ubuntu'
  dir: botfront
  args: ['bash', 'meteor', 'npm', 'start', 'ci']