steps:

- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build',
          '-t', 'botfront:candidate',
          '/workspace']

- name: 'gcr.io/cloud-builders/docker'
  args: ['pull', 'turbolent/duckling:latest']

- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'turbolent/duckling:latest', 'botfront/duckling:latest']

- name: 'gcr.io/cloud-builders/docker'
  args: ['pull', 'cypress/included:3.4.0']

- name: 'botfront/ci-runner:latest'
  entrypoint: 'bash'
  args: ['cloudbuild.sh']

timeout: 30m
