steps:
- name: 'gcr.io/cloud-builders/npm' 
  dir: /workspace/botfront-api
  args: ["install"]
  
- name: 'gcr.io/cloud-builders/npm'
  dir: /workspace/botfront-api
  args: ["run", "test"]

- name: 'gcr.io/cloud-builders/docker'
  args: [ "build",
          "-t", "botfront/botfront-api-local", "./botfront-api"]

- name: 'gcr.io/cloud-builders/docker'
  args: [ "build",  "-t", "botfront-local", "."]

- name: 'gcr.io/kaniko-project/executor:latest'
  dir: /workspace/botfront/cypress
  args:
  - --dockerfile=Dockerfile_cypress
  - --context=/workspace/botfront/cypress
  - --destination=gcr.io/$PROJECT_ID/cypress-runner:latest
  - --cache=true
  - --cache-ttl=24h

- name: docker.io/docker/compose:1.24.1
  dir: /workspace/botfront/cypress
  args:
    - up
    - --abort-on-container-exit
    - --exit-code-from
    - e2e

timeout: 7200s

images:
    - gcr.io/$PROJECT_ID/cypress-runner:latest