steps:
- name: 'gcr.io/cloud-builders/docker'
  # volumes:
  # - name: 'vol1'
  #   path: '$(pwd)/botfront'
  args: ['build', '-f', './ci/Dockerfile.meteor', '-t', 'meteor-runner', './ci']

- name: 'gcr.io/cloud-builders/docker'
  args: ['run', '-v', '/workspace/botfront:/botfront', '-t', 'meteor-runner', 'meteor', 'reset']

- name: 'gcr.io/cloud-builders/docker'
  args: ['run', '-v', '/workspace/botfront:/botfront', '-t', 'meteor-runner', 'meteor', 'npm', 'install']

- name: 'gcr.io/cloud-builders/docker'
  args: ['run', '-v', '/workspace/botfront:/botfront', '-t', 'meteor-runner', 'meteor', 'npm', 'run', 'ci']
