steps:
- name: 'botfront/meteor-base'
  args: ['build', '-f', './ci/Dockerfile.meteor', '-t', 'meteor-runner', '.']
- name: 'meteor-runner'
  dir: './botfront'
  volumes:
  - name: 'vol1'
    path: './botfront'
  args: ['bash', 'meteor', 'npm', 'install']
- name: 'meteor-runner'
  dir: './botfront'
  volumes:
  - name: 'vol1'
    path: './botfront'
  args: ['bash', 'meteor', 'npm', 'start', 'ci']
