
steps:
- name: 'gcr.io/kaniko-project/executor:latest'
  args:
  - --destination=gcr.io/$PROJECT_ID/cypress-runner
  - --cache=true
  - --cache-ttl=12h
  - --dockerfile 
  - Dockerfile.cypress
# - name: 'gcr.io/kaniko-project/executor:latest'
#   args:
#   - --destination=gcr.io/$PROJECT_ID/botfront:e2e
#   - --cache=true
#   - --cache-ttl=12h
- name: 'gcr.io/cloud-builders/docker'
  args: [ "build", "-t", "gcr.io/$PROJECT_ID/botfront:e2e", "."]
- name: gcr.io/$PROJECT_ID/docker-compose
  args:
    - -f 
    - docker-compose-cypress.yml 
    - up
    - --abort-on-container-exit
    - --exit-code-from
    - e2e
timeout: 2700s
# images:
#  - gcr.io/$PROJECT_ID/botfront:e2e
#  - gcr.io/$PROJECT_ID/cypress-runner