steps:
- name: 'gcr.io/cloud-builders/docker'
  # volumes:
  # - name: 'vol1'
  #   path: '$(pwd)/botfront'
  args: ['build', '-f', './ci/Dockerfile.meteor', '-t', 'meteor-runner', '.']
- name: 'meteor-runner'
  dir: '/workspace/botfront'
  # volumes:
  # - name: 'vol1'
  #   path: '$(pwd)/botfront'
