steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ "build",  "-t", "botfront-local", "."]

- name: 'gcr.io/kaniko-project/executor:latest'
  dir: /workspace/botfront/cypress
  args:
  - --dockerfile=Dockerfile_cypress
  - --context=/workspace/botfront/cypress
  - --destination=gcr.io/$PROJECT_ID/cypress-runner:latest
  - --cache=true
  - --cache-ttl=24h

- name: gcr.io/$PROJECT_ID/docker-compose
  dir: /workspace/botfront/cypress
  args:
    - up
    - --abort-on-container-exit
    - --exit-code-from
    - e2e

timeout: 120m

images:
    - gcr.io/$PROJECT_ID/cypress-runner:latest