#############################################################
# Build a Docker image containing the docs site.            #
# The docs will be available on port 80                     #
#############################################################

FROM nginx:alpine
COPY .vuepress/dist /usr/share/nginx/html