#############################################################
# Used to build a containing running the documentation site #
#############################################################

FROM nginx:alpine
COPY .vuepress/dist /usr/share/nginx/html