##########################################################################
# This Dockerfile builds a Cypress image used by the docker-compose file #
##########################################################################

FROM cypress/base:10
WORKDIR /app

# dependencies will be installed only if the package files change
COPY package.json .
COPY package-lock.json .

# by setting CI environment variable we switch the Cypress install messages
# to small "started / finished" and avoid 1000s of lines of progress messages
# https://github.com/cypress-io/cypress/issues/1243
ENV CI=1
RUN npm ci
# verify that Cypress has been installed correctly.
# running this command separately from "cypress run" will also cache its result
# to avoid verifying again when running the tests
RUN npx cypress verify

ENV WAITFORIT_VERSION="v2.4.1"
RUN curl -o /usr/local/bin/waitforit -sSL https://github.com/maxcnunes/waitforit/releases/download/$WAITFORIT_VERSION/waitforit-linux_amd64 && \
    chmod +x /usr/local/bin/waitforit
ENV WAITING_FOR_ADDRESS=http://botfront:3000
ENTRYPOINT ["/bin/bash"]
CMD ["-c", "waitforit -address=$WAITING_FOR_ADDRESS -status=200 -timeout=300 -retry=2000 -debug -- npx cypress run --config video=false"]
