credentials:
  rasa_addons.core.channels.webchat.WebchatInput:
    session_persistence: true
    base_url: https://{PROJECT_NAMESPACE}.{SOCKET_HOST}
    socket_path: /socket.io/
  rasa_addons.core.channels.bot_regression_test.BotRegressionTestInput: {}
instance: http://rasa-service.{PROJECT_NAMESPACE}
bfApiHost: http://botfront-api-service.botfront
endpoints:
  nlg:
    type: rasa_addons.core.nlg.GraphQLNaturalLanguageGenerator
    url: http://botfront-app-service.botfront/graphql
  action_endpoint:
    url: http://actions-service.{PROJECT_NAMESPACE}/webhook
  tracker_store:
    store_type:  rasa_addons.core.tracker_stores.botfront.BotfrontTrackerStore
    url: http://botfront-app-service.botfront/graphql
policies:
  - name: TEDPolicy
    epochs: 50
    max_history: 5
    batch_size: [32, 64]
  - name: RulePolicy
  - name: AugmentedMemoizationPolicy
defaultDomain:
  slots:
    disambiguation_message:
      type: unfeaturized
  actions:
    - action_botfront_disambiguation
    - action_botfront_disambiguation_followup
    - action_botfront_fallback
    - action_botfront_mapping
webhooks:
  restartRasaWebhook:
    name: RestartRasa
    url: ''
    method: POST
  uploadImageWebhook:
    name: UploadImage
    url: ''
    method: POST
  deleteImageWebhook:
    name: DeleteImage
    url: ''
    method: DELETE
  deploymentWebhook:
    name: DeployProject
    url: ''
    method: POST
  reportCrashWebhook:
    name: ReportCrash
    url: ''
    method: POST
  postTraining:
    name: PostTraining
    url: ''
    method: POST
