credentials:
  rasa_addons.core.channels.webchat.WebchatInput:
    session_persistence: true
    base_url: http://localhost:5005
    socket_path: /socket.io/
  rasa_addons.core.channels.bot_regession_test.BotRegressionTestInput: {}
instance: http://rasa:5005
bfApiHost: http://botfront-api:8080
endpoints:
  nlg:
    type: rasa_addons.core.nlg.GraphQLNaturalLanguageGenerator
    url: http://botfront:3000/graphql
  action_endpoint:
    url: http://actions:5055/webhook
  tracker_store:
    store_type:  rasa_addons.core.tracker_stores.botfront.BotfrontTrackerStore
    url: http://botfront:3000/graphql
policies:
  - name: TEDPolicy
    epochs: 50
    max_history: 5
    batch_size: [32, 64]
  - name: RulePolicy
    enable_fallback_prediction: false
  - name: AugmentedMemoizationPolicy
  - name: rasa_addons.core.policies.BotfrontDisambiguationPolicy
    fallback_trigger: 0.30
    disambiguation_trigger: '$0 < 2 * $1'
    disambiguation_template: 'utter_disambiguation'
    n_suggestions: 2
    excluded_intents:
      - ^chitchat\..*
      - ^basics\..*
defaultDomain:
  slots:
    disambiguation_message:
      type: unfeaturized
  actions:
    - action_botfront_disambiguation
    - action_botfront_disambiguation_followup
    - action_botfront_fallback
    - action_botfront_mapping