######################################################################
#  This Dockerfile is used for local development                     #
######################################################################

FROM rasa/rasa-sdk:1.3.2

COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

